#!/usr/bin/env Rscript
# Optional survival analysis using user-supplied expression and clinical data.
# No simulated outcomes are generated by this repository.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 6) {
  stop("Usage: Rscript survival_analysis.R <expression.csv> <clinical.csv> ",
       "<gene> <time_col> <event_col> <out_km.pdf>")
}
expr_file <- args[[1]]
clinical_file <- args[[2]]
gene <- args[[3]]
time_col <- args[[4]]
event_col <- args[[5]]
out_km <- args[[6]]

suppressPackageStartupMessages({
  library(survival)
  library(survminer)
})
expr <- read.csv(expr_file, check.names = FALSE, stringsAsFactors = FALSE)
clinical <- read.csv(clinical_file, check.names = FALSE, stringsAsFactors = FALSE)
if (ncol(expr) < 2 || !"sample_id" %in% names(clinical)) {
  stop("Expression needs a gene column plus samples; clinical needs sample_id.")
}
gene_values <- expr[expr[[1]] == gene, -1, drop = TRUE]
if (length(gene_values) != 1) stop("Gene was not found exactly once: ", gene)
if (!all(c(time_col, event_col) %in% names(clinical))) {
  stop("Clinical table lacks configured time/event columns.")
}
samples <- intersect(names(expr)[-1], as.character(clinical$sample_id))
if (length(samples) < 4) stop("Fewer than four matched samples for survival analysis.")
clinical <- clinical[match(samples, clinical$sample_id), , drop = FALSE]
clinical$expression <- as.numeric(gene_values[match(samples, names(expr)[-1])])
clinical$group <- ifelse(clinical$expression >= median(clinical$expression, na.rm = TRUE),
                         "High", "Low")
clinical$time <- as.numeric(clinical[[time_col]])
clinical$event <- as.numeric(clinical[[event_col]])
if (anyNA(clinical[, c("time", "event", "group")])) stop("Clinical values contain NA.")
fit <- survfit(Surv(time, event) ~ group, data = clinical)
pdf(out_km, width = 7, height = 6)
print(ggsurvplot(fit, data = clinical, pval = TRUE, risk.table = TRUE,
                 title = paste("Survival:", gene)), newpage = FALSE)
dev.off()
